-- MySQL Script generated by MySQL Workbench
-- Tue Sep 21 20:50:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `tipoUsuario` VARCHAR(45) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `identificacion` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NULL,
  `estadoCivil` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NOT NULL,
  PRIMARY KEY (`idUsuarios`),
  UNIQUE INDEX `idUsuarios_UNIQUE` (`idUsuarios` ASC) VISIBLE,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ListaReproducción`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ListaReproducción` (
  `idRockolaEscuchaAdministrador` INT NOT NULL AUTO_INCREMENT,
  `id_ListaReproduccion` VARCHAR(45) NOT NULL,
  `fechaIngreso` DATE NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idRockolaEscuchaAdministrador`),
  UNIQUE INDEX `idAdministrador_UNIQUE` (`idRockolaEscuchaAdministrador` ASC) VISIBLE,
  UNIQUE INDEX `idUsuarioAdministrador_UNIQUE` (`id_ListaReproduccion` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_ListaReproduccion`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Artista` (
  `idArtista` INT NOT NULL AUTO_INCREMENT,
  `nombreArtista` VARCHAR(45) NULL,
  `nacionalidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idArtista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Album` (
  `idAlbum` INT NOT NULL AUTO_INCREMENT,
  `agnio` VARCHAR(45) NULL,
  `nombreAlbum` VARCHAR(45) NULL,
  `idCancion` VARCHAR(45) NOT NULL,
  `Artista_idArtista` INT NOT NULL,
  PRIMARY KEY (`idAlbum`),
  INDEX `fk_Album_Artista1_idx` (`Artista_idArtista` ASC) VISIBLE,
  CONSTRAINT `fk_Album_Artista1`
    FOREIGN KEY (`Artista_idArtista`)
    REFERENCES `mydb`.`Artista` (`idArtista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cancion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cancion` (
  `idCancion` INT NOT NULL AUTO_INCREMENT,
  `nombreCancion` VARCHAR(45) NULL,
  `id_Artista` VARCHAR(45) NULL,
  `id_Album` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `Artista_idArtista` INT NOT NULL,
  PRIMARY KEY (`idCancion`),
  INDEX `fk_Cancion_Artista1_idx` (`Artista_idArtista` ASC) VISIBLE,
  CONSTRAINT `fk_Cancion_Artista1`
    FOREIGN KEY (`Artista_idArtista`)
    REFERENCES `mydb`.`Artista` (`idArtista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ListaCanciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ListaCanciones` (
  `idListaReproduccion` INT NOT NULL,
  `idCancion` INT NOT NULL,
  `ListaReproducción_idRockolaEscuchaAdministrador` INT NOT NULL,
  `Cancion_idCancion` INT NOT NULL,
  INDEX `fk_ListaCanciones_ListaReproducción1_idx` (`ListaReproducción_idRockolaEscuchaAdministrador` ASC) VISIBLE,
  INDEX `fk_ListaCanciones_Cancion1_idx` (`Cancion_idCancion` ASC) VISIBLE,
  CONSTRAINT `fk_ListaReproducción_ListaCanciones`
    FOREIGN KEY (`ListaReproducción_idRockolaEscuchaAdministrador`)
    REFERENCES `mydb`.`ListaReproducción` (`idRockolaEscuchaAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cancion_ListaCanciones`
    FOREIGN KEY (`Cancion_idCancion`)
    REFERENCES `mydb`.`Cancion` (`idCancion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
